STM32CubeProgrammer := 'C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeProgrammer\bin\STM32_Programmer_CLI.exe'

flash: all
	-@echo 'Download hex/bin to MCU Flash ...'
	$(STM32CubeProgrammer) -log flash.log -c port=SWD -d $(wildcard *.hex) -Rst 
#	$(STM32CubeProgrammer) -c port=SWD -d $(wildcard *.bin) 0x8000000 -log flash.log -hardRst

.PHONY: flash 	 